// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhvdczfyfrsddcbdevve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJodmRjemZ5ZnJzZGRjYmRldnZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTE0NzksImV4cCI6MjA2NTQ4NzQ3OX0.whL7jwvjE8RrGCkQ_E8sWdDOT_kSmShmxyiY2bcBUKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);