// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxwjsqnjwjdnawpwotfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4d2pzcW5qd2pkbmF3cHdvdGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTkyMDMsImV4cCI6MjA2NTQ5NTIwM30.z-WdBSm75V8l_r0G_TbrWxlVlI07kpI4-LJ5UtwYw4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);